apiVersion: v1
kind: Service
metadata:
  name: {{ include "pwa-main.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pwa-main.name" . }}
    helm.sh/chart: {{ include "pwa-main.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    prometheus.io/port: "9113"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4200
      protocol: TCP
      name: http
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: prometheus
  selector:
    app.kubernetes.io/name: {{ include "pwa-main.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
